spring:
  application:
    name: campephilus
  profiles:
    active: test
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
    redis:
      repositories:
        enabled: false

server:
  servlet:
    context-path: /campephilus