spring:
  #mongo配置
  data:
    mongodb:
      host: 120.79.151.208
      port: 27017
      username: mrc206
      password: mrc206$mrc206
      database: campephilus
  rabbitmq:
    host: 120.79.151.208
    port: 5672
    password: campephilus
    username: campephilus
    virtual-host: /campephilus

#  redis:
#    # Redis数据库索引（默认为0）
#    database: 0
#    # Redis服务器地址
#    host: 120.79.151.208
#    # Redis服务器连接端口
#    port: 6379
#    # Redis服务器连接密码（默认为空）
#    password: yplBTG6yeu6pw61k
#    # 连接池最大连接数（使用负值表示没有限制）
#    jedis:
#      pool:
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-active: 8
#        # 连接池中的最大空闲连接
#        max-wait: -1
#        # 连接池中的最小空闲连接
#        max-idle: 0
#    # 连接超时时间（毫秒）
##    timeout: 0


server:
  servlet:
    context-path: /campephilus