spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: campephilus
    password: yplBTG6yeu6pw61k
    url: jdbc:mysql://rm-wz90i0nbmc54e83r40o.mysql.rds.aliyuncs.com/campephilus?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    password: guest
    username: guest
    virtual-host: /

#  redis:
#    # Redis数据库索引（默认为0）
#    database: 0
#    # Redis服务器地址
#    host: 120.79.151.208
#    # Redis服务器连接端口
#    port: 6379
#    # Redis服务器连接密码（默认为空）
#    password: yplBTG6yeu6pw61k
#    # 连接池最大连接数（使用负值表示没有限制）
#    jedis:
#      pool:
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-active: 8
#        # 连接池中的最大空闲连接
#        max-wait: -1
#        # 连接池中的最小空闲连接
#        max-idle: 0
#    # 连接超时时间（毫秒）
##    timeout: 0


server:
  servlet:
    context-path: /campephilus