spring:
  #mongo配置
  data:
    mongodb:
      host: 120.79.151.208
      port: 27017
      username: mrc206
      password: mrc206$mrc206
      database: real_data

server:
  servlet:
    context-path: /campephilus