spring:
  application:
    name: campephilus
  profiles:
    active: prod
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
    redis:
      repositories:
        enabled: false
  cloud:
    stream:
      bindings:
        input_campephilus:
          destination: message-campephilus-exchange
        #          content-type: application/x-protobuf
        output_campephilus:
          destination: message-campephilus-exchange
      #          content-type: application/x-protobuf
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: campephilus
                password: campephilus
                virtual-host: /campephilus

server:
  servlet:
    context-path: /campephilus