spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: campephilus
    password: yplBTG6yeu6pw61k
    url: jdbc:mysql://rm-wz90i0nbmc54e83r4968.mysql.rds.aliyuncs.com/campephilus-dev?characterEncoding=utf-8&useSSL=false

  redis:
    host: 120.79.151.208

