spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: campephilus-dev
    password: 2xEt88kaHhbJb2Ce
    url: jdbc:mysql://localhost:3306/campephilus-dev?characterEncoding=utf-8&useSSL=false

  redis:
    host: localhost


