spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: re51YEjoT5bi
    url: jdbc:mariadb://120.79.151.208:3306/real_data?useUnicode=true&characterEncoding=UTF-8&useSSL=false

  jpa:
    database: mysql
    show-sql: true

  #mongo配置
  data:
    mongodb:
      host: 120.79.151.208
      port: 27017
      username: mrc206
      password: mrc206$mrc206
      database: real_data

server:
  servlet:
    context-path: /realData