spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://172.20.29.5:3306/campephilus-dev?characterEncoding=utf-8&useSSL=false

  redis:
    host: 172.20.29.5


