spring:
  application:
    name: campephilus
  profiles:
    active: local
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred

server:
  port: 8081
  servlet:
    context-path: /campephilus