spring:
  application:
    name: campephilus
  profiles:
    active: aliyun
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
    redis:
      repositories:
        enabled: false

server:
  port: 8081
  servlet:
    context-path: /campephilus