spring:
  application:
    name: campephilus
  profiles:
    active: test
  data:
    redis:
      repositories:
        enabled: false
  jackson:
    serialization:
      write-dates-as-timestamps: true

server:
  servlet:
    context-path: /campephilus