spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: campephilus_prod
    password: VSKrH#eY1*WRY9eB
    url: jdbc:mysql://rm-wz90i0nbmc54e83r4968.mysql.rds.aliyuncs.com/campephilus?characterEncoding=utf-8&useSSL=false

  redis:
    host: r-wz97709w2x1bqvu9tn.redis.rds.aliyuncs.com
    password: 7@V8nwnFUKtzBaB6

