spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mariadb://127.0.0.1/iacu?useUnicode=true&characterEncoding=UTF-8&useSSL=false

  jpa:
    database: mysql
    show-sql: true

  #mongo配置
  data:
    mongodb:
      host: 172.20.29.10
      port: 27017
      username: mrc206
      password: mrc206
      database: iacu

server:
  servlet:
    context-path: /realData