spring:
  application:
    name: campephilus
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: campephilus
    password: yplBTG6yeu6pw61k
    url: jdbc:mysql://rm-wz90i0nbmc54e83r40o.mysql.rds.aliyuncs.com/campephilus-test?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: localhost
    port: 5672
    username: campephilus
    password: campephilus
    virtual-host: /campephilus
    publisher-confirms: false
    publisher-returns: false

server:
  servlet:
    context-path: /campephilus