// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol_buffers_patient_info.proto

package org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo;

public final class PatientInfoProtos {
  private PatientInfoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PatientInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:poji.PatientInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     **
     * 标记id，自动增长
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <pre>
     **
     * 病人身份证号
     * </pre>
     *
     * <code>string patientId = 2;</code>
     */
    java.lang.String getPatientId();
    /**
     * <pre>
     **
     * 病人身份证号
     * </pre>
     *
     * <code>string patientId = 2;</code>
     */
    com.google.protobuf.ByteString
        getPatientIdBytes();

    /**
     * <pre>
     **
     * 住院号
     * </pre>
     *
     * <code>string admissionNumber = 3;</code>
     */
    java.lang.String getAdmissionNumber();
    /**
     * <pre>
     **
     * 住院号
     * </pre>
     *
     * <code>string admissionNumber = 3;</code>
     */
    com.google.protobuf.ByteString
        getAdmissionNumberBytes();

    /**
     * <pre>
     **
     * 性别0--男，1--女
     * </pre>
     *
     * <code>int32 sex = 4;</code>
     */
    int getSex();

    /**
     * <pre>
     **
     * 体重
     * </pre>
     *
     * <code>int32 height = 5;</code>
     */
    int getHeight();

    /**
     * <pre>
     **
     * 体重
     * </pre>
     *
     * <code>int32 weight = 6;</code>
     */
    int getWeight();

    /**
     * <pre>
     **
     * 年龄
     * </pre>
     *
     * <code>int32 age = 7;</code>
     */
    int getAge();

    /**
     * <pre>
     **
     * 手术顺序号
     * </pre>
     *
     * <code>int32 operationNumber = 8;</code>
     */
    int getOperationNumber();
  }
  /**
   * Protobuf type {@code poji.PatientInfo}
   */
  public  static final class PatientInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:poji.PatientInfo)
      PatientInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PatientInfo.newBuilder() to construct.
    private PatientInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PatientInfo() {
      patientId_ = "";
      admissionNumber_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PatientInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              patientId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              admissionNumber_ = s;
              break;
            }
            case 32: {

              sex_ = input.readInt32();
              break;
            }
            case 40: {

              height_ = input.readInt32();
              break;
            }
            case 48: {

              weight_ = input.readInt32();
              break;
            }
            case 56: {

              age_ = input.readInt32();
              break;
            }
            case 64: {

              operationNumber_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.internal_static_poji_PatientInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.internal_static_poji_PatientInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo.class, org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     **
     * 标记id，自动增长
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int PATIENTID_FIELD_NUMBER = 2;
    private volatile java.lang.Object patientId_;
    /**
     * <pre>
     **
     * 病人身份证号
     * </pre>
     *
     * <code>string patientId = 2;</code>
     */
    public java.lang.String getPatientId() {
      java.lang.Object ref = patientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        patientId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 病人身份证号
     * </pre>
     *
     * <code>string patientId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPatientIdBytes() {
      java.lang.Object ref = patientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        patientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADMISSIONNUMBER_FIELD_NUMBER = 3;
    private volatile java.lang.Object admissionNumber_;
    /**
     * <pre>
     **
     * 住院号
     * </pre>
     *
     * <code>string admissionNumber = 3;</code>
     */
    public java.lang.String getAdmissionNumber() {
      java.lang.Object ref = admissionNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        admissionNumber_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 住院号
     * </pre>
     *
     * <code>string admissionNumber = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAdmissionNumberBytes() {
      java.lang.Object ref = admissionNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        admissionNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 4;
    private int sex_;
    /**
     * <pre>
     **
     * 性别0--男，1--女
     * </pre>
     *
     * <code>int32 sex = 4;</code>
     */
    public int getSex() {
      return sex_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 5;
    private int height_;
    /**
     * <pre>
     **
     * 体重
     * </pre>
     *
     * <code>int32 height = 5;</code>
     */
    public int getHeight() {
      return height_;
    }

    public static final int WEIGHT_FIELD_NUMBER = 6;
    private int weight_;
    /**
     * <pre>
     **
     * 体重
     * </pre>
     *
     * <code>int32 weight = 6;</code>
     */
    public int getWeight() {
      return weight_;
    }

    public static final int AGE_FIELD_NUMBER = 7;
    private int age_;
    /**
     * <pre>
     **
     * 年龄
     * </pre>
     *
     * <code>int32 age = 7;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int OPERATIONNUMBER_FIELD_NUMBER = 8;
    private int operationNumber_;
    /**
     * <pre>
     **
     * 手术顺序号
     * </pre>
     *
     * <code>int32 operationNumber = 8;</code>
     */
    public int getOperationNumber() {
      return operationNumber_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getPatientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, patientId_);
      }
      if (!getAdmissionNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, admissionNumber_);
      }
      if (sex_ != 0) {
        output.writeInt32(4, sex_);
      }
      if (height_ != 0) {
        output.writeInt32(5, height_);
      }
      if (weight_ != 0) {
        output.writeInt32(6, weight_);
      }
      if (age_ != 0) {
        output.writeInt32(7, age_);
      }
      if (operationNumber_ != 0) {
        output.writeInt32(8, operationNumber_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getPatientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, patientId_);
      }
      if (!getAdmissionNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, admissionNumber_);
      }
      if (sex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, sex_);
      }
      if (height_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, height_);
      }
      if (weight_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, weight_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, age_);
      }
      if (operationNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, operationNumber_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo)) {
        return super.equals(obj);
      }
      org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo other = (org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo) obj;

      if (getId()
          != other.getId()) return false;
      if (!getPatientId()
          .equals(other.getPatientId())) return false;
      if (!getAdmissionNumber()
          .equals(other.getAdmissionNumber())) return false;
      if (getSex()
          != other.getSex()) return false;
      if (getHeight()
          != other.getHeight()) return false;
      if (getWeight()
          != other.getWeight()) return false;
      if (getAge()
          != other.getAge()) return false;
      if (getOperationNumber()
          != other.getOperationNumber()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + PATIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getPatientId().hashCode();
      hash = (37 * hash) + ADMISSIONNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getAdmissionNumber().hashCode();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + getSex();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getHeight();
      hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getWeight();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + OPERATIONNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getOperationNumber();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code poji.PatientInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:poji.PatientInfo)
        org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.internal_static_poji_PatientInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.internal_static_poji_PatientInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo.class, org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo.Builder.class);
      }

      // Construct using org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        patientId_ = "";

        admissionNumber_ = "";

        sex_ = 0;

        height_ = 0;

        weight_ = 0;

        age_ = 0;

        operationNumber_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.internal_static_poji_PatientInfo_descriptor;
      }

      @java.lang.Override
      public org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo getDefaultInstanceForType() {
        return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo.getDefaultInstance();
      }

      @java.lang.Override
      public org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo build() {
        org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo buildPartial() {
        org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo result = new org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo(this);
        result.id_ = id_;
        result.patientId_ = patientId_;
        result.admissionNumber_ = admissionNumber_;
        result.sex_ = sex_;
        result.height_ = height_;
        result.weight_ = weight_;
        result.age_ = age_;
        result.operationNumber_ = operationNumber_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo) {
          return mergeFrom((org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo other) {
        if (other == org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getPatientId().isEmpty()) {
          patientId_ = other.patientId_;
          onChanged();
        }
        if (!other.getAdmissionNumber().isEmpty()) {
          admissionNumber_ = other.admissionNumber_;
          onChanged();
        }
        if (other.getSex() != 0) {
          setSex(other.getSex());
        }
        if (other.getHeight() != 0) {
          setHeight(other.getHeight());
        }
        if (other.getWeight() != 0) {
          setWeight(other.getWeight());
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getOperationNumber() != 0) {
          setOperationNumber(other.getOperationNumber());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       **
       * 标记id，自动增长
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       **
       * 标记id，自动增长
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 标记id，自动增长
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object patientId_ = "";
      /**
       * <pre>
       **
       * 病人身份证号
       * </pre>
       *
       * <code>string patientId = 2;</code>
       */
      public java.lang.String getPatientId() {
        java.lang.Object ref = patientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          patientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 病人身份证号
       * </pre>
       *
       * <code>string patientId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPatientIdBytes() {
        java.lang.Object ref = patientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          patientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 病人身份证号
       * </pre>
       *
       * <code>string patientId = 2;</code>
       */
      public Builder setPatientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        patientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 病人身份证号
       * </pre>
       *
       * <code>string patientId = 2;</code>
       */
      public Builder clearPatientId() {
        
        patientId_ = getDefaultInstance().getPatientId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 病人身份证号
       * </pre>
       *
       * <code>string patientId = 2;</code>
       */
      public Builder setPatientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        patientId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object admissionNumber_ = "";
      /**
       * <pre>
       **
       * 住院号
       * </pre>
       *
       * <code>string admissionNumber = 3;</code>
       */
      public java.lang.String getAdmissionNumber() {
        java.lang.Object ref = admissionNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          admissionNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 住院号
       * </pre>
       *
       * <code>string admissionNumber = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAdmissionNumberBytes() {
        java.lang.Object ref = admissionNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          admissionNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 住院号
       * </pre>
       *
       * <code>string admissionNumber = 3;</code>
       */
      public Builder setAdmissionNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        admissionNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 住院号
       * </pre>
       *
       * <code>string admissionNumber = 3;</code>
       */
      public Builder clearAdmissionNumber() {
        
        admissionNumber_ = getDefaultInstance().getAdmissionNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 住院号
       * </pre>
       *
       * <code>string admissionNumber = 3;</code>
       */
      public Builder setAdmissionNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        admissionNumber_ = value;
        onChanged();
        return this;
      }

      private int sex_ ;
      /**
       * <pre>
       **
       * 性别0--男，1--女
       * </pre>
       *
       * <code>int32 sex = 4;</code>
       */
      public int getSex() {
        return sex_;
      }
      /**
       * <pre>
       **
       * 性别0--男，1--女
       * </pre>
       *
       * <code>int32 sex = 4;</code>
       */
      public Builder setSex(int value) {
        
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 性别0--男，1--女
       * </pre>
       *
       * <code>int32 sex = 4;</code>
       */
      public Builder clearSex() {
        
        sex_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <pre>
       **
       * 体重
       * </pre>
       *
       * <code>int32 height = 5;</code>
       */
      public int getHeight() {
        return height_;
      }
      /**
       * <pre>
       **
       * 体重
       * </pre>
       *
       * <code>int32 height = 5;</code>
       */
      public Builder setHeight(int value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 体重
       * </pre>
       *
       * <code>int32 height = 5;</code>
       */
      public Builder clearHeight() {
        
        height_ = 0;
        onChanged();
        return this;
      }

      private int weight_ ;
      /**
       * <pre>
       **
       * 体重
       * </pre>
       *
       * <code>int32 weight = 6;</code>
       */
      public int getWeight() {
        return weight_;
      }
      /**
       * <pre>
       **
       * 体重
       * </pre>
       *
       * <code>int32 weight = 6;</code>
       */
      public Builder setWeight(int value) {
        
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 体重
       * </pre>
       *
       * <code>int32 weight = 6;</code>
       */
      public Builder clearWeight() {
        
        weight_ = 0;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <pre>
       **
       * 年龄
       * </pre>
       *
       * <code>int32 age = 7;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <pre>
       **
       * 年龄
       * </pre>
       *
       * <code>int32 age = 7;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 年龄
       * </pre>
       *
       * <code>int32 age = 7;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private int operationNumber_ ;
      /**
       * <pre>
       **
       * 手术顺序号
       * </pre>
       *
       * <code>int32 operationNumber = 8;</code>
       */
      public int getOperationNumber() {
        return operationNumber_;
      }
      /**
       * <pre>
       **
       * 手术顺序号
       * </pre>
       *
       * <code>int32 operationNumber = 8;</code>
       */
      public Builder setOperationNumber(int value) {
        
        operationNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 手术顺序号
       * </pre>
       *
       * <code>int32 operationNumber = 8;</code>
       */
      public Builder clearOperationNumber() {
        
        operationNumber_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:poji.PatientInfo)
    }

    // @@protoc_insertion_point(class_scope:poji.PatientInfo)
    private static final org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo();
    }

    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PatientInfo>
        PARSER = new com.google.protobuf.AbstractParser<PatientInfo>() {
      @java.lang.Override
      public PatientInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PatientInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PatientInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PatientInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.PatientInfoProtos.PatientInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_poji_PatientInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_poji_PatientInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#protocol_buffers_patient_info.proto\022\004p" +
      "oji\"\230\001\n\013PatientInfo\022\n\n\002id\030\001 \001(\005\022\021\n\tpatie" +
      "ntId\030\002 \001(\t\022\027\n\017admissionNumber\030\003 \001(\t\022\013\n\003s" +
      "ex\030\004 \001(\005\022\016\n\006height\030\005 \001(\005\022\016\n\006weight\030\006 \001(\005" +
      "\022\013\n\003age\030\007 \001(\005\022\027\n\017operationNumber\030\010 \001(\005BZ" +
      "\nEorg.cqu.edu.msc.annihilation.campephil" +
      "us.module.message.protobuf.pojoB\021Patient" +
      "InfoProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_poji_PatientInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_poji_PatientInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_poji_PatientInfo_descriptor,
        new java.lang.String[] { "Id", "PatientId", "AdmissionNumber", "Sex", "Height", "Weight", "Age", "OperationNumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
