// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf_before_operation_info.proto

package org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo;

public final class ProtobufBeforeOperationInfo {
  private ProtobufBeforeOperationInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BeforeOperationInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.BeforeOperationInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     **
     * 标记id，自动增长
     * </pre>
     *
     * <code>int32 beforeOperationId = 1;</code>
     */
    int getBeforeOperationId();

    /**
     * <pre>
     **
     * 麻醉方式
     * </pre>
     *
     * <code>string anesthesiaMode = 2;</code>
     */
    java.lang.String getAnesthesiaMode();
    /**
     * <pre>
     **
     * 麻醉方式
     * </pre>
     *
     * <code>string anesthesiaMode = 2;</code>
     */
    com.google.protobuf.ByteString
        getAnesthesiaModeBytes();

    /**
     * <pre>
     **
     * 是否急诊
     * </pre>
     *
     * <code>bool isUrgent = 3;</code>
     */
    boolean getIsUrgent();

    /**
     * <pre>
     **
     * 是否增强
     * </pre>
     *
     * <code>bool isStrong = 4;</code>
     */
    boolean getIsStrong();

    /**
     * <pre>
     **
     * ASA等级
     * </pre>
     *
     * <code>int32 ASALevel = 5;</code>
     */
    int getASALevel();

    /**
     * <pre>
     **
     * 既往病史
     * </pre>
     *
     * <code>string medicalHistory = 6;</code>
     */
    java.lang.String getMedicalHistory();
    /**
     * <pre>
     **
     * 既往病史
     * </pre>
     *
     * <code>string medicalHistory = 6;</code>
     */
    com.google.protobuf.ByteString
        getMedicalHistoryBytes();

    /**
     * <pre>
     **
     * 特殊情况
     * </pre>
     *
     * <code>string specialCase = 7;</code>
     */
    java.lang.String getSpecialCase();
    /**
     * <pre>
     **
     * 特殊情况
     * </pre>
     *
     * <code>string specialCase = 7;</code>
     */
    com.google.protobuf.ByteString
        getSpecialCaseBytes();

    /**
     * <pre>
     **
     * 住院号
     * </pre>
     *
     * <code>string admissionNumber = 8;</code>
     */
    java.lang.String getAdmissionNumber();
    /**
     * <pre>
     **
     * 住院号
     * </pre>
     *
     * <code>string admissionNumber = 8;</code>
     */
    com.google.protobuf.ByteString
        getAdmissionNumberBytes();
  }
  /**
   * Protobuf type {@code org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.BeforeOperationInfo}
   */
  public  static final class BeforeOperationInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.BeforeOperationInfo)
      BeforeOperationInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BeforeOperationInfo.newBuilder() to construct.
    private BeforeOperationInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BeforeOperationInfo() {
      anesthesiaMode_ = "";
      medicalHistory_ = "";
      specialCase_ = "";
      admissionNumber_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BeforeOperationInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              beforeOperationId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              anesthesiaMode_ = s;
              break;
            }
            case 24: {

              isUrgent_ = input.readBool();
              break;
            }
            case 32: {

              isStrong_ = input.readBool();
              break;
            }
            case 40: {

              aSALevel_ = input.readInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              medicalHistory_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              specialCase_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              admissionNumber_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_BeforeOperationInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_BeforeOperationInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo.class, org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo.Builder.class);
    }

    public static final int BEFOREOPERATIONID_FIELD_NUMBER = 1;
    private int beforeOperationId_;
    /**
     * <pre>
     **
     * 标记id，自动增长
     * </pre>
     *
     * <code>int32 beforeOperationId = 1;</code>
     */
    public int getBeforeOperationId() {
      return beforeOperationId_;
    }

    public static final int ANESTHESIAMODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object anesthesiaMode_;
    /**
     * <pre>
     **
     * 麻醉方式
     * </pre>
     *
     * <code>string anesthesiaMode = 2;</code>
     */
    public java.lang.String getAnesthesiaMode() {
      java.lang.Object ref = anesthesiaMode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        anesthesiaMode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 麻醉方式
     * </pre>
     *
     * <code>string anesthesiaMode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAnesthesiaModeBytes() {
      java.lang.Object ref = anesthesiaMode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        anesthesiaMode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISURGENT_FIELD_NUMBER = 3;
    private boolean isUrgent_;
    /**
     * <pre>
     **
     * 是否急诊
     * </pre>
     *
     * <code>bool isUrgent = 3;</code>
     */
    public boolean getIsUrgent() {
      return isUrgent_;
    }

    public static final int ISSTRONG_FIELD_NUMBER = 4;
    private boolean isStrong_;
    /**
     * <pre>
     **
     * 是否增强
     * </pre>
     *
     * <code>bool isStrong = 4;</code>
     */
    public boolean getIsStrong() {
      return isStrong_;
    }

    public static final int ASALEVEL_FIELD_NUMBER = 5;
    private int aSALevel_;
    /**
     * <pre>
     **
     * ASA等级
     * </pre>
     *
     * <code>int32 ASALevel = 5;</code>
     */
    public int getASALevel() {
      return aSALevel_;
    }

    public static final int MEDICALHISTORY_FIELD_NUMBER = 6;
    private volatile java.lang.Object medicalHistory_;
    /**
     * <pre>
     **
     * 既往病史
     * </pre>
     *
     * <code>string medicalHistory = 6;</code>
     */
    public java.lang.String getMedicalHistory() {
      java.lang.Object ref = medicalHistory_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        medicalHistory_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 既往病史
     * </pre>
     *
     * <code>string medicalHistory = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMedicalHistoryBytes() {
      java.lang.Object ref = medicalHistory_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        medicalHistory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SPECIALCASE_FIELD_NUMBER = 7;
    private volatile java.lang.Object specialCase_;
    /**
     * <pre>
     **
     * 特殊情况
     * </pre>
     *
     * <code>string specialCase = 7;</code>
     */
    public java.lang.String getSpecialCase() {
      java.lang.Object ref = specialCase_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        specialCase_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 特殊情况
     * </pre>
     *
     * <code>string specialCase = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSpecialCaseBytes() {
      java.lang.Object ref = specialCase_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        specialCase_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADMISSIONNUMBER_FIELD_NUMBER = 8;
    private volatile java.lang.Object admissionNumber_;
    /**
     * <pre>
     **
     * 住院号
     * </pre>
     *
     * <code>string admissionNumber = 8;</code>
     */
    public java.lang.String getAdmissionNumber() {
      java.lang.Object ref = admissionNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        admissionNumber_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 住院号
     * </pre>
     *
     * <code>string admissionNumber = 8;</code>
     */
    public com.google.protobuf.ByteString
        getAdmissionNumberBytes() {
      java.lang.Object ref = admissionNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        admissionNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (beforeOperationId_ != 0) {
        output.writeInt32(1, beforeOperationId_);
      }
      if (!getAnesthesiaModeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, anesthesiaMode_);
      }
      if (isUrgent_ != false) {
        output.writeBool(3, isUrgent_);
      }
      if (isStrong_ != false) {
        output.writeBool(4, isStrong_);
      }
      if (aSALevel_ != 0) {
        output.writeInt32(5, aSALevel_);
      }
      if (!getMedicalHistoryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, medicalHistory_);
      }
      if (!getSpecialCaseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, specialCase_);
      }
      if (!getAdmissionNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, admissionNumber_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (beforeOperationId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, beforeOperationId_);
      }
      if (!getAnesthesiaModeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, anesthesiaMode_);
      }
      if (isUrgent_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isUrgent_);
      }
      if (isStrong_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isStrong_);
      }
      if (aSALevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, aSALevel_);
      }
      if (!getMedicalHistoryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, medicalHistory_);
      }
      if (!getSpecialCaseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, specialCase_);
      }
      if (!getAdmissionNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, admissionNumber_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo)) {
        return super.equals(obj);
      }
      org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo other = (org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo) obj;

      if (getBeforeOperationId()
          != other.getBeforeOperationId()) return false;
      if (!getAnesthesiaMode()
          .equals(other.getAnesthesiaMode())) return false;
      if (getIsUrgent()
          != other.getIsUrgent()) return false;
      if (getIsStrong()
          != other.getIsStrong()) return false;
      if (getASALevel()
          != other.getASALevel()) return false;
      if (!getMedicalHistory()
          .equals(other.getMedicalHistory())) return false;
      if (!getSpecialCase()
          .equals(other.getSpecialCase())) return false;
      if (!getAdmissionNumber()
          .equals(other.getAdmissionNumber())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BEFOREOPERATIONID_FIELD_NUMBER;
      hash = (53 * hash) + getBeforeOperationId();
      hash = (37 * hash) + ANESTHESIAMODE_FIELD_NUMBER;
      hash = (53 * hash) + getAnesthesiaMode().hashCode();
      hash = (37 * hash) + ISURGENT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsUrgent());
      hash = (37 * hash) + ISSTRONG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsStrong());
      hash = (37 * hash) + ASALEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getASALevel();
      hash = (37 * hash) + MEDICALHISTORY_FIELD_NUMBER;
      hash = (53 * hash) + getMedicalHistory().hashCode();
      hash = (37 * hash) + SPECIALCASE_FIELD_NUMBER;
      hash = (53 * hash) + getSpecialCase().hashCode();
      hash = (37 * hash) + ADMISSIONNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getAdmissionNumber().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.BeforeOperationInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.BeforeOperationInfo)
        org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_BeforeOperationInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_BeforeOperationInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo.class, org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo.Builder.class);
      }

      // Construct using org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        beforeOperationId_ = 0;

        anesthesiaMode_ = "";

        isUrgent_ = false;

        isStrong_ = false;

        aSALevel_ = 0;

        medicalHistory_ = "";

        specialCase_ = "";

        admissionNumber_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_BeforeOperationInfo_descriptor;
      }

      @java.lang.Override
      public org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo getDefaultInstanceForType() {
        return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo.getDefaultInstance();
      }

      @java.lang.Override
      public org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo build() {
        org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo buildPartial() {
        org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo result = new org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo(this);
        result.beforeOperationId_ = beforeOperationId_;
        result.anesthesiaMode_ = anesthesiaMode_;
        result.isUrgent_ = isUrgent_;
        result.isStrong_ = isStrong_;
        result.aSALevel_ = aSALevel_;
        result.medicalHistory_ = medicalHistory_;
        result.specialCase_ = specialCase_;
        result.admissionNumber_ = admissionNumber_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo) {
          return mergeFrom((org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo other) {
        if (other == org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo.getDefaultInstance()) return this;
        if (other.getBeforeOperationId() != 0) {
          setBeforeOperationId(other.getBeforeOperationId());
        }
        if (!other.getAnesthesiaMode().isEmpty()) {
          anesthesiaMode_ = other.anesthesiaMode_;
          onChanged();
        }
        if (other.getIsUrgent() != false) {
          setIsUrgent(other.getIsUrgent());
        }
        if (other.getIsStrong() != false) {
          setIsStrong(other.getIsStrong());
        }
        if (other.getASALevel() != 0) {
          setASALevel(other.getASALevel());
        }
        if (!other.getMedicalHistory().isEmpty()) {
          medicalHistory_ = other.medicalHistory_;
          onChanged();
        }
        if (!other.getSpecialCase().isEmpty()) {
          specialCase_ = other.specialCase_;
          onChanged();
        }
        if (!other.getAdmissionNumber().isEmpty()) {
          admissionNumber_ = other.admissionNumber_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int beforeOperationId_ ;
      /**
       * <pre>
       **
       * 标记id，自动增长
       * </pre>
       *
       * <code>int32 beforeOperationId = 1;</code>
       */
      public int getBeforeOperationId() {
        return beforeOperationId_;
      }
      /**
       * <pre>
       **
       * 标记id，自动增长
       * </pre>
       *
       * <code>int32 beforeOperationId = 1;</code>
       */
      public Builder setBeforeOperationId(int value) {
        
        beforeOperationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 标记id，自动增长
       * </pre>
       *
       * <code>int32 beforeOperationId = 1;</code>
       */
      public Builder clearBeforeOperationId() {
        
        beforeOperationId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object anesthesiaMode_ = "";
      /**
       * <pre>
       **
       * 麻醉方式
       * </pre>
       *
       * <code>string anesthesiaMode = 2;</code>
       */
      public java.lang.String getAnesthesiaMode() {
        java.lang.Object ref = anesthesiaMode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          anesthesiaMode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 麻醉方式
       * </pre>
       *
       * <code>string anesthesiaMode = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAnesthesiaModeBytes() {
        java.lang.Object ref = anesthesiaMode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          anesthesiaMode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 麻醉方式
       * </pre>
       *
       * <code>string anesthesiaMode = 2;</code>
       */
      public Builder setAnesthesiaMode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        anesthesiaMode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 麻醉方式
       * </pre>
       *
       * <code>string anesthesiaMode = 2;</code>
       */
      public Builder clearAnesthesiaMode() {
        
        anesthesiaMode_ = getDefaultInstance().getAnesthesiaMode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 麻醉方式
       * </pre>
       *
       * <code>string anesthesiaMode = 2;</code>
       */
      public Builder setAnesthesiaModeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        anesthesiaMode_ = value;
        onChanged();
        return this;
      }

      private boolean isUrgent_ ;
      /**
       * <pre>
       **
       * 是否急诊
       * </pre>
       *
       * <code>bool isUrgent = 3;</code>
       */
      public boolean getIsUrgent() {
        return isUrgent_;
      }
      /**
       * <pre>
       **
       * 是否急诊
       * </pre>
       *
       * <code>bool isUrgent = 3;</code>
       */
      public Builder setIsUrgent(boolean value) {
        
        isUrgent_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 是否急诊
       * </pre>
       *
       * <code>bool isUrgent = 3;</code>
       */
      public Builder clearIsUrgent() {
        
        isUrgent_ = false;
        onChanged();
        return this;
      }

      private boolean isStrong_ ;
      /**
       * <pre>
       **
       * 是否增强
       * </pre>
       *
       * <code>bool isStrong = 4;</code>
       */
      public boolean getIsStrong() {
        return isStrong_;
      }
      /**
       * <pre>
       **
       * 是否增强
       * </pre>
       *
       * <code>bool isStrong = 4;</code>
       */
      public Builder setIsStrong(boolean value) {
        
        isStrong_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 是否增强
       * </pre>
       *
       * <code>bool isStrong = 4;</code>
       */
      public Builder clearIsStrong() {
        
        isStrong_ = false;
        onChanged();
        return this;
      }

      private int aSALevel_ ;
      /**
       * <pre>
       **
       * ASA等级
       * </pre>
       *
       * <code>int32 ASALevel = 5;</code>
       */
      public int getASALevel() {
        return aSALevel_;
      }
      /**
       * <pre>
       **
       * ASA等级
       * </pre>
       *
       * <code>int32 ASALevel = 5;</code>
       */
      public Builder setASALevel(int value) {
        
        aSALevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * ASA等级
       * </pre>
       *
       * <code>int32 ASALevel = 5;</code>
       */
      public Builder clearASALevel() {
        
        aSALevel_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object medicalHistory_ = "";
      /**
       * <pre>
       **
       * 既往病史
       * </pre>
       *
       * <code>string medicalHistory = 6;</code>
       */
      public java.lang.String getMedicalHistory() {
        java.lang.Object ref = medicalHistory_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          medicalHistory_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 既往病史
       * </pre>
       *
       * <code>string medicalHistory = 6;</code>
       */
      public com.google.protobuf.ByteString
          getMedicalHistoryBytes() {
        java.lang.Object ref = medicalHistory_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          medicalHistory_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 既往病史
       * </pre>
       *
       * <code>string medicalHistory = 6;</code>
       */
      public Builder setMedicalHistory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        medicalHistory_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 既往病史
       * </pre>
       *
       * <code>string medicalHistory = 6;</code>
       */
      public Builder clearMedicalHistory() {
        
        medicalHistory_ = getDefaultInstance().getMedicalHistory();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 既往病史
       * </pre>
       *
       * <code>string medicalHistory = 6;</code>
       */
      public Builder setMedicalHistoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        medicalHistory_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object specialCase_ = "";
      /**
       * <pre>
       **
       * 特殊情况
       * </pre>
       *
       * <code>string specialCase = 7;</code>
       */
      public java.lang.String getSpecialCase() {
        java.lang.Object ref = specialCase_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          specialCase_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 特殊情况
       * </pre>
       *
       * <code>string specialCase = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSpecialCaseBytes() {
        java.lang.Object ref = specialCase_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          specialCase_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 特殊情况
       * </pre>
       *
       * <code>string specialCase = 7;</code>
       */
      public Builder setSpecialCase(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        specialCase_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 特殊情况
       * </pre>
       *
       * <code>string specialCase = 7;</code>
       */
      public Builder clearSpecialCase() {
        
        specialCase_ = getDefaultInstance().getSpecialCase();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 特殊情况
       * </pre>
       *
       * <code>string specialCase = 7;</code>
       */
      public Builder setSpecialCaseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        specialCase_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object admissionNumber_ = "";
      /**
       * <pre>
       **
       * 住院号
       * </pre>
       *
       * <code>string admissionNumber = 8;</code>
       */
      public java.lang.String getAdmissionNumber() {
        java.lang.Object ref = admissionNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          admissionNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 住院号
       * </pre>
       *
       * <code>string admissionNumber = 8;</code>
       */
      public com.google.protobuf.ByteString
          getAdmissionNumberBytes() {
        java.lang.Object ref = admissionNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          admissionNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 住院号
       * </pre>
       *
       * <code>string admissionNumber = 8;</code>
       */
      public Builder setAdmissionNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        admissionNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 住院号
       * </pre>
       *
       * <code>string admissionNumber = 8;</code>
       */
      public Builder clearAdmissionNumber() {
        
        admissionNumber_ = getDefaultInstance().getAdmissionNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 住院号
       * </pre>
       *
       * <code>string admissionNumber = 8;</code>
       */
      public Builder setAdmissionNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        admissionNumber_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.BeforeOperationInfo)
    }

    // @@protoc_insertion_point(class_scope:org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.BeforeOperationInfo)
    private static final org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo();
    }

    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BeforeOperationInfo>
        PARSER = new com.google.protobuf.AbstractParser<BeforeOperationInfo>() {
      @java.lang.Override
      public BeforeOperationInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BeforeOperationInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BeforeOperationInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BeforeOperationInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufBeforeOperationInfo.BeforeOperationInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_BeforeOperationInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_BeforeOperationInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$protobuf_before_operation_info.proto\022E" +
      "org.cqu.edu.msc.annihilation.campephilus" +
      ".module.message.protobuf.pojo\"\304\001\n\023Before" +
      "OperationInfo\022\031\n\021beforeOperationId\030\001 \001(\005" +
      "\022\026\n\016anesthesiaMode\030\002 \001(\t\022\020\n\010isUrgent\030\003 \001" +
      "(\010\022\020\n\010isStrong\030\004 \001(\010\022\020\n\010ASALevel\030\005 \001(\005\022\026" +
      "\n\016medicalHistory\030\006 \001(\t\022\023\n\013specialCase\030\007 " +
      "\001(\t\022\027\n\017admissionNumber\030\010 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_BeforeOperationInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_BeforeOperationInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_BeforeOperationInfo_descriptor,
        new java.lang.String[] { "BeforeOperationId", "AnesthesiaMode", "IsUrgent", "IsStrong", "ASALevel", "MedicalHistory", "SpecialCase", "AdmissionNumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
