// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf_operation_mark_info.proto

package org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo;

public final class ProtobufOperationMarkInfo {
  private ProtobufOperationMarkInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OperationMarkInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.OperationMarkInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     **
     * 标记id，自动增长
     * </pre>
     *
     * <code>int32 markId = 1;</code>
     */
    int getMarkId();

    /**
     * <pre>
     **
     * 标记类型
     * </pre>
     *
     * <code>int32 markType = 2;</code>
     */
    int getMarkType();

    /**
     * <pre>
     **
     * 事件类型
     * </pre>
     *
     * <code>string eventType = 3;</code>
     */
    java.lang.String getEventType();
    /**
     * <pre>
     **
     * 事件类型
     * </pre>
     *
     * <code>string eventType = 3;</code>
     */
    com.google.protobuf.ByteString
        getEventTypeBytes();

    /**
     * <pre>
     **
     * 事件
     * </pre>
     *
     * <code>string event = 4;</code>
     */
    java.lang.String getEvent();
    /**
     * <pre>
     **
     * 事件
     * </pre>
     *
     * <code>string event = 4;</code>
     */
    com.google.protobuf.ByteString
        getEventBytes();

    /**
     * <pre>
     **
     * 途径
     * </pre>
     *
     * <code>string way = 5;</code>
     */
    java.lang.String getWay();
    /**
     * <pre>
     **
     * 途径
     * </pre>
     *
     * <code>string way = 5;</code>
     */
    com.google.protobuf.ByteString
        getWayBytes();

    /**
     * <pre>
     **
     * 剂量
     * </pre>
     *
     * <code>string dose = 6;</code>
     */
    java.lang.String getDose();
    /**
     * <pre>
     **
     * 剂量
     * </pre>
     *
     * <code>string dose = 6;</code>
     */
    com.google.protobuf.ByteString
        getDoseBytes();

    /**
     * <pre>
     **
     * 不良反应/特殊情况
     * </pre>
     *
     * <code>string specialSituation = 7;</code>
     */
    java.lang.String getSpecialSituation();
    /**
     * <pre>
     **
     * 不良反应/特殊情况
     * </pre>
     *
     * <code>string specialSituation = 7;</code>
     */
    com.google.protobuf.ByteString
        getSpecialSituationBytes();

    /**
     * <pre>
     **
     * 标记信息标记的时间
     * </pre>
     *
     * <code>int64 markTime = 8;</code>
     */
    long getMarkTime();

    /**
     * <pre>
     **
     * 手术顺序号
     * </pre>
     *
     * <code>int32 operationId = 9;</code>
     */
    int getOperationId();
  }
  /**
   * Protobuf type {@code org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.OperationMarkInfo}
   */
  public  static final class OperationMarkInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.OperationMarkInfo)
      OperationMarkInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OperationMarkInfo.newBuilder() to construct.
    private OperationMarkInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OperationMarkInfo() {
      eventType_ = "";
      event_ = "";
      way_ = "";
      dose_ = "";
      specialSituation_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OperationMarkInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              markId_ = input.readInt32();
              break;
            }
            case 16: {

              markType_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              eventType_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              event_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              way_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              dose_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              specialSituation_ = s;
              break;
            }
            case 64: {

              markTime_ = input.readInt64();
              break;
            }
            case 72: {

              operationId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_OperationMarkInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_OperationMarkInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo.class, org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo.Builder.class);
    }

    public static final int MARKID_FIELD_NUMBER = 1;
    private int markId_;
    /**
     * <pre>
     **
     * 标记id，自动增长
     * </pre>
     *
     * <code>int32 markId = 1;</code>
     */
    public int getMarkId() {
      return markId_;
    }

    public static final int MARKTYPE_FIELD_NUMBER = 2;
    private int markType_;
    /**
     * <pre>
     **
     * 标记类型
     * </pre>
     *
     * <code>int32 markType = 2;</code>
     */
    public int getMarkType() {
      return markType_;
    }

    public static final int EVENTTYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object eventType_;
    /**
     * <pre>
     **
     * 事件类型
     * </pre>
     *
     * <code>string eventType = 3;</code>
     */
    public java.lang.String getEventType() {
      java.lang.Object ref = eventType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 事件类型
     * </pre>
     *
     * <code>string eventType = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEventTypeBytes() {
      java.lang.Object ref = eventType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENT_FIELD_NUMBER = 4;
    private volatile java.lang.Object event_;
    /**
     * <pre>
     **
     * 事件
     * </pre>
     *
     * <code>string event = 4;</code>
     */
    public java.lang.String getEvent() {
      java.lang.Object ref = event_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        event_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 事件
     * </pre>
     *
     * <code>string event = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEventBytes() {
      java.lang.Object ref = event_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        event_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WAY_FIELD_NUMBER = 5;
    private volatile java.lang.Object way_;
    /**
     * <pre>
     **
     * 途径
     * </pre>
     *
     * <code>string way = 5;</code>
     */
    public java.lang.String getWay() {
      java.lang.Object ref = way_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        way_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 途径
     * </pre>
     *
     * <code>string way = 5;</code>
     */
    public com.google.protobuf.ByteString
        getWayBytes() {
      java.lang.Object ref = way_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        way_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOSE_FIELD_NUMBER = 6;
    private volatile java.lang.Object dose_;
    /**
     * <pre>
     **
     * 剂量
     * </pre>
     *
     * <code>string dose = 6;</code>
     */
    public java.lang.String getDose() {
      java.lang.Object ref = dose_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dose_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 剂量
     * </pre>
     *
     * <code>string dose = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDoseBytes() {
      java.lang.Object ref = dose_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dose_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SPECIALSITUATION_FIELD_NUMBER = 7;
    private volatile java.lang.Object specialSituation_;
    /**
     * <pre>
     **
     * 不良反应/特殊情况
     * </pre>
     *
     * <code>string specialSituation = 7;</code>
     */
    public java.lang.String getSpecialSituation() {
      java.lang.Object ref = specialSituation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        specialSituation_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 不良反应/特殊情况
     * </pre>
     *
     * <code>string specialSituation = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSpecialSituationBytes() {
      java.lang.Object ref = specialSituation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        specialSituation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MARKTIME_FIELD_NUMBER = 8;
    private long markTime_;
    /**
     * <pre>
     **
     * 标记信息标记的时间
     * </pre>
     *
     * <code>int64 markTime = 8;</code>
     */
    public long getMarkTime() {
      return markTime_;
    }

    public static final int OPERATIONID_FIELD_NUMBER = 9;
    private int operationId_;
    /**
     * <pre>
     **
     * 手术顺序号
     * </pre>
     *
     * <code>int32 operationId = 9;</code>
     */
    public int getOperationId() {
      return operationId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (markId_ != 0) {
        output.writeInt32(1, markId_);
      }
      if (markType_ != 0) {
        output.writeInt32(2, markType_);
      }
      if (!getEventTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, eventType_);
      }
      if (!getEventBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, event_);
      }
      if (!getWayBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, way_);
      }
      if (!getDoseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, dose_);
      }
      if (!getSpecialSituationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, specialSituation_);
      }
      if (markTime_ != 0L) {
        output.writeInt64(8, markTime_);
      }
      if (operationId_ != 0) {
        output.writeInt32(9, operationId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (markId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, markId_);
      }
      if (markType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, markType_);
      }
      if (!getEventTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, eventType_);
      }
      if (!getEventBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, event_);
      }
      if (!getWayBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, way_);
      }
      if (!getDoseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, dose_);
      }
      if (!getSpecialSituationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, specialSituation_);
      }
      if (markTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, markTime_);
      }
      if (operationId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, operationId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo)) {
        return super.equals(obj);
      }
      org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo other = (org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo) obj;

      if (getMarkId()
          != other.getMarkId()) return false;
      if (getMarkType()
          != other.getMarkType()) return false;
      if (!getEventType()
          .equals(other.getEventType())) return false;
      if (!getEvent()
          .equals(other.getEvent())) return false;
      if (!getWay()
          .equals(other.getWay())) return false;
      if (!getDose()
          .equals(other.getDose())) return false;
      if (!getSpecialSituation()
          .equals(other.getSpecialSituation())) return false;
      if (getMarkTime()
          != other.getMarkTime()) return false;
      if (getOperationId()
          != other.getOperationId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MARKID_FIELD_NUMBER;
      hash = (53 * hash) + getMarkId();
      hash = (37 * hash) + MARKTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMarkType();
      hash = (37 * hash) + EVENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getEventType().hashCode();
      hash = (37 * hash) + EVENT_FIELD_NUMBER;
      hash = (53 * hash) + getEvent().hashCode();
      hash = (37 * hash) + WAY_FIELD_NUMBER;
      hash = (53 * hash) + getWay().hashCode();
      hash = (37 * hash) + DOSE_FIELD_NUMBER;
      hash = (53 * hash) + getDose().hashCode();
      hash = (37 * hash) + SPECIALSITUATION_FIELD_NUMBER;
      hash = (53 * hash) + getSpecialSituation().hashCode();
      hash = (37 * hash) + MARKTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMarkTime());
      hash = (37 * hash) + OPERATIONID_FIELD_NUMBER;
      hash = (53 * hash) + getOperationId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.OperationMarkInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.OperationMarkInfo)
        org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_OperationMarkInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_OperationMarkInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo.class, org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo.Builder.class);
      }

      // Construct using org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        markId_ = 0;

        markType_ = 0;

        eventType_ = "";

        event_ = "";

        way_ = "";

        dose_ = "";

        specialSituation_ = "";

        markTime_ = 0L;

        operationId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_OperationMarkInfo_descriptor;
      }

      @java.lang.Override
      public org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo getDefaultInstanceForType() {
        return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo.getDefaultInstance();
      }

      @java.lang.Override
      public org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo build() {
        org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo buildPartial() {
        org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo result = new org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo(this);
        result.markId_ = markId_;
        result.markType_ = markType_;
        result.eventType_ = eventType_;
        result.event_ = event_;
        result.way_ = way_;
        result.dose_ = dose_;
        result.specialSituation_ = specialSituation_;
        result.markTime_ = markTime_;
        result.operationId_ = operationId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo) {
          return mergeFrom((org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo other) {
        if (other == org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo.getDefaultInstance()) return this;
        if (other.getMarkId() != 0) {
          setMarkId(other.getMarkId());
        }
        if (other.getMarkType() != 0) {
          setMarkType(other.getMarkType());
        }
        if (!other.getEventType().isEmpty()) {
          eventType_ = other.eventType_;
          onChanged();
        }
        if (!other.getEvent().isEmpty()) {
          event_ = other.event_;
          onChanged();
        }
        if (!other.getWay().isEmpty()) {
          way_ = other.way_;
          onChanged();
        }
        if (!other.getDose().isEmpty()) {
          dose_ = other.dose_;
          onChanged();
        }
        if (!other.getSpecialSituation().isEmpty()) {
          specialSituation_ = other.specialSituation_;
          onChanged();
        }
        if (other.getMarkTime() != 0L) {
          setMarkTime(other.getMarkTime());
        }
        if (other.getOperationId() != 0) {
          setOperationId(other.getOperationId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int markId_ ;
      /**
       * <pre>
       **
       * 标记id，自动增长
       * </pre>
       *
       * <code>int32 markId = 1;</code>
       */
      public int getMarkId() {
        return markId_;
      }
      /**
       * <pre>
       **
       * 标记id，自动增长
       * </pre>
       *
       * <code>int32 markId = 1;</code>
       */
      public Builder setMarkId(int value) {
        
        markId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 标记id，自动增长
       * </pre>
       *
       * <code>int32 markId = 1;</code>
       */
      public Builder clearMarkId() {
        
        markId_ = 0;
        onChanged();
        return this;
      }

      private int markType_ ;
      /**
       * <pre>
       **
       * 标记类型
       * </pre>
       *
       * <code>int32 markType = 2;</code>
       */
      public int getMarkType() {
        return markType_;
      }
      /**
       * <pre>
       **
       * 标记类型
       * </pre>
       *
       * <code>int32 markType = 2;</code>
       */
      public Builder setMarkType(int value) {
        
        markType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 标记类型
       * </pre>
       *
       * <code>int32 markType = 2;</code>
       */
      public Builder clearMarkType() {
        
        markType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object eventType_ = "";
      /**
       * <pre>
       **
       * 事件类型
       * </pre>
       *
       * <code>string eventType = 3;</code>
       */
      public java.lang.String getEventType() {
        java.lang.Object ref = eventType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eventType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 事件类型
       * </pre>
       *
       * <code>string eventType = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEventTypeBytes() {
        java.lang.Object ref = eventType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eventType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 事件类型
       * </pre>
       *
       * <code>string eventType = 3;</code>
       */
      public Builder setEventType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        eventType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 事件类型
       * </pre>
       *
       * <code>string eventType = 3;</code>
       */
      public Builder clearEventType() {
        
        eventType_ = getDefaultInstance().getEventType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 事件类型
       * </pre>
       *
       * <code>string eventType = 3;</code>
       */
      public Builder setEventTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        eventType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object event_ = "";
      /**
       * <pre>
       **
       * 事件
       * </pre>
       *
       * <code>string event = 4;</code>
       */
      public java.lang.String getEvent() {
        java.lang.Object ref = event_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          event_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 事件
       * </pre>
       *
       * <code>string event = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEventBytes() {
        java.lang.Object ref = event_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          event_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 事件
       * </pre>
       *
       * <code>string event = 4;</code>
       */
      public Builder setEvent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        event_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 事件
       * </pre>
       *
       * <code>string event = 4;</code>
       */
      public Builder clearEvent() {
        
        event_ = getDefaultInstance().getEvent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 事件
       * </pre>
       *
       * <code>string event = 4;</code>
       */
      public Builder setEventBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        event_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object way_ = "";
      /**
       * <pre>
       **
       * 途径
       * </pre>
       *
       * <code>string way = 5;</code>
       */
      public java.lang.String getWay() {
        java.lang.Object ref = way_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          way_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 途径
       * </pre>
       *
       * <code>string way = 5;</code>
       */
      public com.google.protobuf.ByteString
          getWayBytes() {
        java.lang.Object ref = way_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          way_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 途径
       * </pre>
       *
       * <code>string way = 5;</code>
       */
      public Builder setWay(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        way_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 途径
       * </pre>
       *
       * <code>string way = 5;</code>
       */
      public Builder clearWay() {
        
        way_ = getDefaultInstance().getWay();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 途径
       * </pre>
       *
       * <code>string way = 5;</code>
       */
      public Builder setWayBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        way_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dose_ = "";
      /**
       * <pre>
       **
       * 剂量
       * </pre>
       *
       * <code>string dose = 6;</code>
       */
      public java.lang.String getDose() {
        java.lang.Object ref = dose_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dose_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 剂量
       * </pre>
       *
       * <code>string dose = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDoseBytes() {
        java.lang.Object ref = dose_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dose_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 剂量
       * </pre>
       *
       * <code>string dose = 6;</code>
       */
      public Builder setDose(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dose_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 剂量
       * </pre>
       *
       * <code>string dose = 6;</code>
       */
      public Builder clearDose() {
        
        dose_ = getDefaultInstance().getDose();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 剂量
       * </pre>
       *
       * <code>string dose = 6;</code>
       */
      public Builder setDoseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dose_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object specialSituation_ = "";
      /**
       * <pre>
       **
       * 不良反应/特殊情况
       * </pre>
       *
       * <code>string specialSituation = 7;</code>
       */
      public java.lang.String getSpecialSituation() {
        java.lang.Object ref = specialSituation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          specialSituation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 不良反应/特殊情况
       * </pre>
       *
       * <code>string specialSituation = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSpecialSituationBytes() {
        java.lang.Object ref = specialSituation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          specialSituation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 不良反应/特殊情况
       * </pre>
       *
       * <code>string specialSituation = 7;</code>
       */
      public Builder setSpecialSituation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        specialSituation_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 不良反应/特殊情况
       * </pre>
       *
       * <code>string specialSituation = 7;</code>
       */
      public Builder clearSpecialSituation() {
        
        specialSituation_ = getDefaultInstance().getSpecialSituation();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 不良反应/特殊情况
       * </pre>
       *
       * <code>string specialSituation = 7;</code>
       */
      public Builder setSpecialSituationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        specialSituation_ = value;
        onChanged();
        return this;
      }

      private long markTime_ ;
      /**
       * <pre>
       **
       * 标记信息标记的时间
       * </pre>
       *
       * <code>int64 markTime = 8;</code>
       */
      public long getMarkTime() {
        return markTime_;
      }
      /**
       * <pre>
       **
       * 标记信息标记的时间
       * </pre>
       *
       * <code>int64 markTime = 8;</code>
       */
      public Builder setMarkTime(long value) {
        
        markTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 标记信息标记的时间
       * </pre>
       *
       * <code>int64 markTime = 8;</code>
       */
      public Builder clearMarkTime() {
        
        markTime_ = 0L;
        onChanged();
        return this;
      }

      private int operationId_ ;
      /**
       * <pre>
       **
       * 手术顺序号
       * </pre>
       *
       * <code>int32 operationId = 9;</code>
       */
      public int getOperationId() {
        return operationId_;
      }
      /**
       * <pre>
       **
       * 手术顺序号
       * </pre>
       *
       * <code>int32 operationId = 9;</code>
       */
      public Builder setOperationId(int value) {
        
        operationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 手术顺序号
       * </pre>
       *
       * <code>int32 operationId = 9;</code>
       */
      public Builder clearOperationId() {
        
        operationId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.OperationMarkInfo)
    }

    // @@protoc_insertion_point(class_scope:org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.OperationMarkInfo)
    private static final org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo();
    }

    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OperationMarkInfo>
        PARSER = new com.google.protobuf.AbstractParser<OperationMarkInfo>() {
      @java.lang.Override
      public OperationMarkInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OperationMarkInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OperationMarkInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OperationMarkInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationMarkInfo.OperationMarkInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_OperationMarkInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_OperationMarkInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"protobuf_operation_mark_info.proto\022Eor" +
      "g.cqu.edu.msc.annihilation.campephilus.m" +
      "odule.message.protobuf.pojo\"\263\001\n\021Operatio" +
      "nMarkInfo\022\016\n\006markId\030\001 \001(\005\022\020\n\010markType\030\002 " +
      "\001(\005\022\021\n\teventType\030\003 \001(\t\022\r\n\005event\030\004 \001(\t\022\013\n" +
      "\003way\030\005 \001(\t\022\014\n\004dose\030\006 \001(\t\022\030\n\020specialSitua" +
      "tion\030\007 \001(\t\022\020\n\010markTime\030\010 \001(\003\022\023\n\013operatio" +
      "nId\030\t \001(\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_OperationMarkInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_OperationMarkInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_OperationMarkInfo_descriptor,
        new java.lang.String[] { "MarkId", "MarkType", "EventType", "Event", "Way", "Dose", "SpecialSituation", "MarkTime", "OperationId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
