// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf_operation_info.proto

package org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo;

public final class ProtobufOperationInfo {
  private ProtobufOperationInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OperationInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.OperationInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     **
     * 手术顺序号
     * </pre>
     *
     * <code>int32 operationNumber = 1;</code>
     */
    int getOperationNumber();

    /**
     * <pre>
     **
     * 手术名称
     * </pre>
     *
     * <code>string operationName = 2;</code>
     */
    java.lang.String getOperationName();
    /**
     * <pre>
     **
     * 手术名称
     * </pre>
     *
     * <code>string operationName = 2;</code>
     */
    com.google.protobuf.ByteString
        getOperationNameBytes();

    /**
     * <pre>
     **
     * 手术开始时间
     * </pre>
     *
     * <code>int64 operationStartTime = 3;</code>
     */
    long getOperationStartTime();

    /**
     * <pre>
     **
     * 手术结束时间
     * </pre>
     *
     * <code>int64 operationEndTime = 4;</code>
     */
    long getOperationEndTime();

    /**
     * <pre>
     **
     * 手术设备，直接保存了JSON字符串
     * </pre>
     *
     * <code>string operationDevice = 5;</code>
     */
    java.lang.String getOperationDevice();
    /**
     * <pre>
     **
     * 手术设备，直接保存了JSON字符串
     * </pre>
     *
     * <code>string operationDevice = 5;</code>
     */
    com.google.protobuf.ByteString
        getOperationDeviceBytes();

    /**
     * <pre>
     **
     * 手术状态
     * </pre>
     *
     * <code>int32 operationState = 6;</code>
     */
    int getOperationState();
  }
  /**
   * Protobuf type {@code org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.OperationInfo}
   */
  public  static final class OperationInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.OperationInfo)
      OperationInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OperationInfo.newBuilder() to construct.
    private OperationInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OperationInfo() {
      operationName_ = "";
      operationDevice_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OperationInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              operationNumber_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              operationName_ = s;
              break;
            }
            case 24: {

              operationStartTime_ = input.readInt64();
              break;
            }
            case 32: {

              operationEndTime_ = input.readInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              operationDevice_ = s;
              break;
            }
            case 48: {

              operationState_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_OperationInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_OperationInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo.class, org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo.Builder.class);
    }

    public static final int OPERATIONNUMBER_FIELD_NUMBER = 1;
    private int operationNumber_;
    /**
     * <pre>
     **
     * 手术顺序号
     * </pre>
     *
     * <code>int32 operationNumber = 1;</code>
     */
    public int getOperationNumber() {
      return operationNumber_;
    }

    public static final int OPERATIONNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object operationName_;
    /**
     * <pre>
     **
     * 手术名称
     * </pre>
     *
     * <code>string operationName = 2;</code>
     */
    public java.lang.String getOperationName() {
      java.lang.Object ref = operationName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operationName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 手术名称
     * </pre>
     *
     * <code>string operationName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOperationNameBytes() {
      java.lang.Object ref = operationName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERATIONSTARTTIME_FIELD_NUMBER = 3;
    private long operationStartTime_;
    /**
     * <pre>
     **
     * 手术开始时间
     * </pre>
     *
     * <code>int64 operationStartTime = 3;</code>
     */
    public long getOperationStartTime() {
      return operationStartTime_;
    }

    public static final int OPERATIONENDTIME_FIELD_NUMBER = 4;
    private long operationEndTime_;
    /**
     * <pre>
     **
     * 手术结束时间
     * </pre>
     *
     * <code>int64 operationEndTime = 4;</code>
     */
    public long getOperationEndTime() {
      return operationEndTime_;
    }

    public static final int OPERATIONDEVICE_FIELD_NUMBER = 5;
    private volatile java.lang.Object operationDevice_;
    /**
     * <pre>
     **
     * 手术设备，直接保存了JSON字符串
     * </pre>
     *
     * <code>string operationDevice = 5;</code>
     */
    public java.lang.String getOperationDevice() {
      java.lang.Object ref = operationDevice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operationDevice_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 手术设备，直接保存了JSON字符串
     * </pre>
     *
     * <code>string operationDevice = 5;</code>
     */
    public com.google.protobuf.ByteString
        getOperationDeviceBytes() {
      java.lang.Object ref = operationDevice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operationDevice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERATIONSTATE_FIELD_NUMBER = 6;
    private int operationState_;
    /**
     * <pre>
     **
     * 手术状态
     * </pre>
     *
     * <code>int32 operationState = 6;</code>
     */
    public int getOperationState() {
      return operationState_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (operationNumber_ != 0) {
        output.writeInt32(1, operationNumber_);
      }
      if (!getOperationNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, operationName_);
      }
      if (operationStartTime_ != 0L) {
        output.writeInt64(3, operationStartTime_);
      }
      if (operationEndTime_ != 0L) {
        output.writeInt64(4, operationEndTime_);
      }
      if (!getOperationDeviceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, operationDevice_);
      }
      if (operationState_ != 0) {
        output.writeInt32(6, operationState_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (operationNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, operationNumber_);
      }
      if (!getOperationNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, operationName_);
      }
      if (operationStartTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, operationStartTime_);
      }
      if (operationEndTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, operationEndTime_);
      }
      if (!getOperationDeviceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, operationDevice_);
      }
      if (operationState_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, operationState_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo)) {
        return super.equals(obj);
      }
      org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo other = (org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo) obj;

      if (getOperationNumber()
          != other.getOperationNumber()) return false;
      if (!getOperationName()
          .equals(other.getOperationName())) return false;
      if (getOperationStartTime()
          != other.getOperationStartTime()) return false;
      if (getOperationEndTime()
          != other.getOperationEndTime()) return false;
      if (!getOperationDevice()
          .equals(other.getOperationDevice())) return false;
      if (getOperationState()
          != other.getOperationState()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPERATIONNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getOperationNumber();
      hash = (37 * hash) + OPERATIONNAME_FIELD_NUMBER;
      hash = (53 * hash) + getOperationName().hashCode();
      hash = (37 * hash) + OPERATIONSTARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOperationStartTime());
      hash = (37 * hash) + OPERATIONENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOperationEndTime());
      hash = (37 * hash) + OPERATIONDEVICE_FIELD_NUMBER;
      hash = (53 * hash) + getOperationDevice().hashCode();
      hash = (37 * hash) + OPERATIONSTATE_FIELD_NUMBER;
      hash = (53 * hash) + getOperationState();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.OperationInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.OperationInfo)
        org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_OperationInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_OperationInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo.class, org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo.Builder.class);
      }

      // Construct using org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        operationNumber_ = 0;

        operationName_ = "";

        operationStartTime_ = 0L;

        operationEndTime_ = 0L;

        operationDevice_ = "";

        operationState_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_OperationInfo_descriptor;
      }

      @java.lang.Override
      public org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo getDefaultInstanceForType() {
        return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo.getDefaultInstance();
      }

      @java.lang.Override
      public org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo build() {
        org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo buildPartial() {
        org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo result = new org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo(this);
        result.operationNumber_ = operationNumber_;
        result.operationName_ = operationName_;
        result.operationStartTime_ = operationStartTime_;
        result.operationEndTime_ = operationEndTime_;
        result.operationDevice_ = operationDevice_;
        result.operationState_ = operationState_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo) {
          return mergeFrom((org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo other) {
        if (other == org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo.getDefaultInstance()) return this;
        if (other.getOperationNumber() != 0) {
          setOperationNumber(other.getOperationNumber());
        }
        if (!other.getOperationName().isEmpty()) {
          operationName_ = other.operationName_;
          onChanged();
        }
        if (other.getOperationStartTime() != 0L) {
          setOperationStartTime(other.getOperationStartTime());
        }
        if (other.getOperationEndTime() != 0L) {
          setOperationEndTime(other.getOperationEndTime());
        }
        if (!other.getOperationDevice().isEmpty()) {
          operationDevice_ = other.operationDevice_;
          onChanged();
        }
        if (other.getOperationState() != 0) {
          setOperationState(other.getOperationState());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int operationNumber_ ;
      /**
       * <pre>
       **
       * 手术顺序号
       * </pre>
       *
       * <code>int32 operationNumber = 1;</code>
       */
      public int getOperationNumber() {
        return operationNumber_;
      }
      /**
       * <pre>
       **
       * 手术顺序号
       * </pre>
       *
       * <code>int32 operationNumber = 1;</code>
       */
      public Builder setOperationNumber(int value) {
        
        operationNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 手术顺序号
       * </pre>
       *
       * <code>int32 operationNumber = 1;</code>
       */
      public Builder clearOperationNumber() {
        
        operationNumber_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object operationName_ = "";
      /**
       * <pre>
       **
       * 手术名称
       * </pre>
       *
       * <code>string operationName = 2;</code>
       */
      public java.lang.String getOperationName() {
        java.lang.Object ref = operationName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          operationName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 手术名称
       * </pre>
       *
       * <code>string operationName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOperationNameBytes() {
        java.lang.Object ref = operationName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operationName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 手术名称
       * </pre>
       *
       * <code>string operationName = 2;</code>
       */
      public Builder setOperationName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        operationName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 手术名称
       * </pre>
       *
       * <code>string operationName = 2;</code>
       */
      public Builder clearOperationName() {
        
        operationName_ = getDefaultInstance().getOperationName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 手术名称
       * </pre>
       *
       * <code>string operationName = 2;</code>
       */
      public Builder setOperationNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        operationName_ = value;
        onChanged();
        return this;
      }

      private long operationStartTime_ ;
      /**
       * <pre>
       **
       * 手术开始时间
       * </pre>
       *
       * <code>int64 operationStartTime = 3;</code>
       */
      public long getOperationStartTime() {
        return operationStartTime_;
      }
      /**
       * <pre>
       **
       * 手术开始时间
       * </pre>
       *
       * <code>int64 operationStartTime = 3;</code>
       */
      public Builder setOperationStartTime(long value) {
        
        operationStartTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 手术开始时间
       * </pre>
       *
       * <code>int64 operationStartTime = 3;</code>
       */
      public Builder clearOperationStartTime() {
        
        operationStartTime_ = 0L;
        onChanged();
        return this;
      }

      private long operationEndTime_ ;
      /**
       * <pre>
       **
       * 手术结束时间
       * </pre>
       *
       * <code>int64 operationEndTime = 4;</code>
       */
      public long getOperationEndTime() {
        return operationEndTime_;
      }
      /**
       * <pre>
       **
       * 手术结束时间
       * </pre>
       *
       * <code>int64 operationEndTime = 4;</code>
       */
      public Builder setOperationEndTime(long value) {
        
        operationEndTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 手术结束时间
       * </pre>
       *
       * <code>int64 operationEndTime = 4;</code>
       */
      public Builder clearOperationEndTime() {
        
        operationEndTime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object operationDevice_ = "";
      /**
       * <pre>
       **
       * 手术设备，直接保存了JSON字符串
       * </pre>
       *
       * <code>string operationDevice = 5;</code>
       */
      public java.lang.String getOperationDevice() {
        java.lang.Object ref = operationDevice_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          operationDevice_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 手术设备，直接保存了JSON字符串
       * </pre>
       *
       * <code>string operationDevice = 5;</code>
       */
      public com.google.protobuf.ByteString
          getOperationDeviceBytes() {
        java.lang.Object ref = operationDevice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operationDevice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 手术设备，直接保存了JSON字符串
       * </pre>
       *
       * <code>string operationDevice = 5;</code>
       */
      public Builder setOperationDevice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        operationDevice_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 手术设备，直接保存了JSON字符串
       * </pre>
       *
       * <code>string operationDevice = 5;</code>
       */
      public Builder clearOperationDevice() {
        
        operationDevice_ = getDefaultInstance().getOperationDevice();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 手术设备，直接保存了JSON字符串
       * </pre>
       *
       * <code>string operationDevice = 5;</code>
       */
      public Builder setOperationDeviceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        operationDevice_ = value;
        onChanged();
        return this;
      }

      private int operationState_ ;
      /**
       * <pre>
       **
       * 手术状态
       * </pre>
       *
       * <code>int32 operationState = 6;</code>
       */
      public int getOperationState() {
        return operationState_;
      }
      /**
       * <pre>
       **
       * 手术状态
       * </pre>
       *
       * <code>int32 operationState = 6;</code>
       */
      public Builder setOperationState(int value) {
        
        operationState_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 手术状态
       * </pre>
       *
       * <code>int32 operationState = 6;</code>
       */
      public Builder clearOperationState() {
        
        operationState_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.OperationInfo)
    }

    // @@protoc_insertion_point(class_scope:org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.OperationInfo)
    private static final org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo();
    }

    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OperationInfo>
        PARSER = new com.google.protobuf.AbstractParser<OperationInfo>() {
      @java.lang.Override
      public OperationInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OperationInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OperationInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OperationInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufOperationInfo.OperationInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_OperationInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_OperationInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035protobuf_operation_info.proto\022Eorg.cqu" +
      ".edu.msc.annihilation.campephilus.module" +
      ".message.protobuf.pojo\"\246\001\n\rOperationInfo" +
      "\022\027\n\017operationNumber\030\001 \001(\005\022\025\n\roperationNa" +
      "me\030\002 \001(\t\022\032\n\022operationStartTime\030\003 \001(\003\022\030\n\020" +
      "operationEndTime\030\004 \001(\003\022\027\n\017operationDevic" +
      "e\030\005 \001(\t\022\026\n\016operationState\030\006 \001(\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_OperationInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_OperationInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_OperationInfo_descriptor,
        new java.lang.String[] { "OperationNumber", "OperationName", "OperationStartTime", "OperationEndTime", "OperationDevice", "OperationState", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
