// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf_device_info.proto

package org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo;

public final class ProtobufDeviceInfo {
  private ProtobufDeviceInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DeviceInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.DeviceInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     **
     * 自动增长ID
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <pre>
     **
     * 设备生产厂商
     * </pre>
     *
     * <code>string deviceCode = 2;</code>
     */
    java.lang.String getDeviceCode();
    /**
     * <pre>
     **
     * 设备生产厂商
     * </pre>
     *
     * <code>string deviceCode = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeviceCodeBytes();

    /**
     * <pre>
     **
     * 设备序列号，不一定唯一
     * </pre>
     *
     * <code>string deviceSerialNumber = 3;</code>
     */
    java.lang.String getDeviceSerialNumber();
    /**
     * <pre>
     **
     * 设备序列号，不一定唯一
     * </pre>
     *
     * <code>string deviceSerialNumber = 3;</code>
     */
    com.google.protobuf.ByteString
        getDeviceSerialNumberBytes();

    /**
     * <pre>
     **
     * 设备购买时间
     * </pre>
     *
     * <code>string deviceProduceDate = 4;</code>
     */
    java.lang.String getDeviceProduceDate();
    /**
     * <pre>
     **
     * 设备购买时间
     * </pre>
     *
     * <code>string deviceProduceDate = 4;</code>
     */
    com.google.protobuf.ByteString
        getDeviceProduceDateBytes();

    /**
     * <pre>
     **
     * 仪器的使用年限
     * </pre>
     *
     * <code>float deviceServiceLife = 5;</code>
     */
    float getDeviceServiceLife();
  }
  /**
   * Protobuf type {@code org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.DeviceInfo}
   */
  public  static final class DeviceInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.DeviceInfo)
      DeviceInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeviceInfo.newBuilder() to construct.
    private DeviceInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeviceInfo() {
      deviceCode_ = "";
      deviceSerialNumber_ = "";
      deviceProduceDate_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceCode_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceSerialNumber_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceProduceDate_ = s;
              break;
            }
            case 45: {

              deviceServiceLife_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_DeviceInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_DeviceInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo.class, org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     **
     * 自动增长ID
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int DEVICECODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object deviceCode_;
    /**
     * <pre>
     **
     * 设备生产厂商
     * </pre>
     *
     * <code>string deviceCode = 2;</code>
     */
    public java.lang.String getDeviceCode() {
      java.lang.Object ref = deviceCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 设备生产厂商
     * </pre>
     *
     * <code>string deviceCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceCodeBytes() {
      java.lang.Object ref = deviceCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICESERIALNUMBER_FIELD_NUMBER = 3;
    private volatile java.lang.Object deviceSerialNumber_;
    /**
     * <pre>
     **
     * 设备序列号，不一定唯一
     * </pre>
     *
     * <code>string deviceSerialNumber = 3;</code>
     */
    public java.lang.String getDeviceSerialNumber() {
      java.lang.Object ref = deviceSerialNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceSerialNumber_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 设备序列号，不一定唯一
     * </pre>
     *
     * <code>string deviceSerialNumber = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceSerialNumberBytes() {
      java.lang.Object ref = deviceSerialNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceSerialNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICEPRODUCEDATE_FIELD_NUMBER = 4;
    private volatile java.lang.Object deviceProduceDate_;
    /**
     * <pre>
     **
     * 设备购买时间
     * </pre>
     *
     * <code>string deviceProduceDate = 4;</code>
     */
    public java.lang.String getDeviceProduceDate() {
      java.lang.Object ref = deviceProduceDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceProduceDate_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 设备购买时间
     * </pre>
     *
     * <code>string deviceProduceDate = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceProduceDateBytes() {
      java.lang.Object ref = deviceProduceDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceProduceDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICESERVICELIFE_FIELD_NUMBER = 5;
    private float deviceServiceLife_;
    /**
     * <pre>
     **
     * 仪器的使用年限
     * </pre>
     *
     * <code>float deviceServiceLife = 5;</code>
     */
    public float getDeviceServiceLife() {
      return deviceServiceLife_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getDeviceCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceCode_);
      }
      if (!getDeviceSerialNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, deviceSerialNumber_);
      }
      if (!getDeviceProduceDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, deviceProduceDate_);
      }
      if (deviceServiceLife_ != 0F) {
        output.writeFloat(5, deviceServiceLife_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getDeviceCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceCode_);
      }
      if (!getDeviceSerialNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, deviceSerialNumber_);
      }
      if (!getDeviceProduceDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, deviceProduceDate_);
      }
      if (deviceServiceLife_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, deviceServiceLife_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo)) {
        return super.equals(obj);
      }
      org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo other = (org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo) obj;

      if (getId()
          != other.getId()) return false;
      if (!getDeviceCode()
          .equals(other.getDeviceCode())) return false;
      if (!getDeviceSerialNumber()
          .equals(other.getDeviceSerialNumber())) return false;
      if (!getDeviceProduceDate()
          .equals(other.getDeviceProduceDate())) return false;
      if (java.lang.Float.floatToIntBits(getDeviceServiceLife())
          != java.lang.Float.floatToIntBits(
              other.getDeviceServiceLife())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + DEVICECODE_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceCode().hashCode();
      hash = (37 * hash) + DEVICESERIALNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceSerialNumber().hashCode();
      hash = (37 * hash) + DEVICEPRODUCEDATE_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceProduceDate().hashCode();
      hash = (37 * hash) + DEVICESERVICELIFE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getDeviceServiceLife());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.DeviceInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.DeviceInfo)
        org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_DeviceInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_DeviceInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo.class, org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo.Builder.class);
      }

      // Construct using org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        deviceCode_ = "";

        deviceSerialNumber_ = "";

        deviceProduceDate_ = "";

        deviceServiceLife_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_DeviceInfo_descriptor;
      }

      @java.lang.Override
      public org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo getDefaultInstanceForType() {
        return org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo.getDefaultInstance();
      }

      @java.lang.Override
      public org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo build() {
        org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo buildPartial() {
        org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo result = new org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo(this);
        result.id_ = id_;
        result.deviceCode_ = deviceCode_;
        result.deviceSerialNumber_ = deviceSerialNumber_;
        result.deviceProduceDate_ = deviceProduceDate_;
        result.deviceServiceLife_ = deviceServiceLife_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo) {
          return mergeFrom((org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo other) {
        if (other == org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getDeviceCode().isEmpty()) {
          deviceCode_ = other.deviceCode_;
          onChanged();
        }
        if (!other.getDeviceSerialNumber().isEmpty()) {
          deviceSerialNumber_ = other.deviceSerialNumber_;
          onChanged();
        }
        if (!other.getDeviceProduceDate().isEmpty()) {
          deviceProduceDate_ = other.deviceProduceDate_;
          onChanged();
        }
        if (other.getDeviceServiceLife() != 0F) {
          setDeviceServiceLife(other.getDeviceServiceLife());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       **
       * 自动增长ID
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       **
       * 自动增长ID
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 自动增长ID
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object deviceCode_ = "";
      /**
       * <pre>
       **
       * 设备生产厂商
       * </pre>
       *
       * <code>string deviceCode = 2;</code>
       */
      public java.lang.String getDeviceCode() {
        java.lang.Object ref = deviceCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 设备生产厂商
       * </pre>
       *
       * <code>string deviceCode = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceCodeBytes() {
        java.lang.Object ref = deviceCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 设备生产厂商
       * </pre>
       *
       * <code>string deviceCode = 2;</code>
       */
      public Builder setDeviceCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 设备生产厂商
       * </pre>
       *
       * <code>string deviceCode = 2;</code>
       */
      public Builder clearDeviceCode() {
        
        deviceCode_ = getDefaultInstance().getDeviceCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 设备生产厂商
       * </pre>
       *
       * <code>string deviceCode = 2;</code>
       */
      public Builder setDeviceCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deviceSerialNumber_ = "";
      /**
       * <pre>
       **
       * 设备序列号，不一定唯一
       * </pre>
       *
       * <code>string deviceSerialNumber = 3;</code>
       */
      public java.lang.String getDeviceSerialNumber() {
        java.lang.Object ref = deviceSerialNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceSerialNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 设备序列号，不一定唯一
       * </pre>
       *
       * <code>string deviceSerialNumber = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceSerialNumberBytes() {
        java.lang.Object ref = deviceSerialNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceSerialNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 设备序列号，不一定唯一
       * </pre>
       *
       * <code>string deviceSerialNumber = 3;</code>
       */
      public Builder setDeviceSerialNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceSerialNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 设备序列号，不一定唯一
       * </pre>
       *
       * <code>string deviceSerialNumber = 3;</code>
       */
      public Builder clearDeviceSerialNumber() {
        
        deviceSerialNumber_ = getDefaultInstance().getDeviceSerialNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 设备序列号，不一定唯一
       * </pre>
       *
       * <code>string deviceSerialNumber = 3;</code>
       */
      public Builder setDeviceSerialNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceSerialNumber_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deviceProduceDate_ = "";
      /**
       * <pre>
       **
       * 设备购买时间
       * </pre>
       *
       * <code>string deviceProduceDate = 4;</code>
       */
      public java.lang.String getDeviceProduceDate() {
        java.lang.Object ref = deviceProduceDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceProduceDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 设备购买时间
       * </pre>
       *
       * <code>string deviceProduceDate = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceProduceDateBytes() {
        java.lang.Object ref = deviceProduceDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceProduceDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 设备购买时间
       * </pre>
       *
       * <code>string deviceProduceDate = 4;</code>
       */
      public Builder setDeviceProduceDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceProduceDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 设备购买时间
       * </pre>
       *
       * <code>string deviceProduceDate = 4;</code>
       */
      public Builder clearDeviceProduceDate() {
        
        deviceProduceDate_ = getDefaultInstance().getDeviceProduceDate();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 设备购买时间
       * </pre>
       *
       * <code>string deviceProduceDate = 4;</code>
       */
      public Builder setDeviceProduceDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceProduceDate_ = value;
        onChanged();
        return this;
      }

      private float deviceServiceLife_ ;
      /**
       * <pre>
       **
       * 仪器的使用年限
       * </pre>
       *
       * <code>float deviceServiceLife = 5;</code>
       */
      public float getDeviceServiceLife() {
        return deviceServiceLife_;
      }
      /**
       * <pre>
       **
       * 仪器的使用年限
       * </pre>
       *
       * <code>float deviceServiceLife = 5;</code>
       */
      public Builder setDeviceServiceLife(float value) {
        
        deviceServiceLife_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 仪器的使用年限
       * </pre>
       *
       * <code>float deviceServiceLife = 5;</code>
       */
      public Builder clearDeviceServiceLife() {
        
        deviceServiceLife_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.DeviceInfo)
    }

    // @@protoc_insertion_point(class_scope:org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.DeviceInfo)
    private static final org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo();
    }

    public static org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeviceInfo>
        PARSER = new com.google.protobuf.AbstractParser<DeviceInfo>() {
      @java.lang.Override
      public DeviceInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeviceInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.cqu.edu.msc.annihilation.campephilus.module.message.protobuf.pojo.ProtobufDeviceInfo.DeviceInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_DeviceInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_DeviceInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032protobuf_device_info.proto\022Eorg.cqu.ed" +
      "u.msc.annihilation.campephilus.module.me" +
      "ssage.protobuf.pojo\"~\n\nDeviceInfo\022\n\n\002id\030" +
      "\001 \001(\005\022\022\n\ndeviceCode\030\002 \001(\t\022\032\n\022deviceSeria" +
      "lNumber\030\003 \001(\t\022\031\n\021deviceProduceDate\030\004 \001(\t" +
      "\022\031\n\021deviceServiceLife\030\005 \001(\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_DeviceInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_DeviceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_cqu_edu_msc_annihilation_campephilus_module_message_protobuf_pojo_DeviceInfo_descriptor,
        new java.lang.String[] { "Id", "DeviceCode", "DeviceSerialNumber", "DeviceProduceDate", "DeviceServiceLife", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
